<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <LangVersion>latest</LangVersion>
    <AssemblyName>DNGuard.Engine</AssemblyName>
    <RootNamespace>DNGuard.Engine</RootNamespace>
    <Version>0.8.6</Version>
    <Deterministic>true</Deterministic>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="dnlib">
      <HintPath>lib\dnlib.dll</HintPath>
      <Private>true</Private>
    </Reference>
  </ItemGroup>
</Project>
